// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Web_de_Nominas.Data;

#nullable disable

namespace Sistema_Web_de_Nominas.Migrations
{
    [DbContext(typeof(NominaDbContext))]
    [Migration("20251125003634_Subida2")]
    partial class Subida2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Empleado", b =>
                {
                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Cedula");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Nomina", b =>
                {
                    b.Property<int>("CodigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoId"));

                    b.Property<decimal>("Devengado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("EmpleadoCedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("HorasExtras")
                        .HasColumnType("float");

                    b.Property<decimal>("INSSLaboral")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Inasistencia")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoDeHorasExtras")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MontoDeducciones")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CodigoId");

                    b.HasIndex("EmpleadoCedula");

                    b.ToTable("Nomina");
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraRecargaToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CorreoConfirmacion")
                        .HasColumnType("bit");

                    b.Property<string>("CorreoConfirmacionToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecargaToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecargaTokenExpirado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReincioTokenExpirado")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Empleado", b =>
                {
                    b.HasOne("Sistema_Web_de_Nominas.Models.Usuario", "Usuario")
                        .WithMany("Empleados")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Nomina", b =>
                {
                    b.HasOne("Sistema_Web_de_Nominas.Models.Empleado", "Empleado")
                        .WithMany("Nominas")
                        .HasForeignKey("EmpleadoCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Usuario", b =>
                {
                    b.HasOne("Sistema_Web_de_Nominas.Models.Rol", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Empleado", b =>
                {
                    b.Navigation("Nominas");
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Rol", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_Web_de_Nominas.Models.Usuario", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
